---
- hosts: local
  tasks:
  - name: Tap caskroom/versions
    homebrew_tap: tap=caskroom/versions
  - name: Update & upgrade Homebrew
    homebrew: update_homebrew=yes upgrade_all=yes
  # Essentials
  - name: Install Bash-Completion
    homebrew: name=bash-completion state=present
  - name: Install Git
    homebrew: name=git state=present
  # Browsers
  - name: Install Firefox
    homebrew_cask: name=firefox state=present
  - name: Install Google Chrome
    homebrew_cask: name=google-chrome state=present
  # Java
  - name: Install Java
    homebrew_cask: name=java state=present
  - name: Install jEnv
    homebrew: name=jenv state=present
  # Ruby
  - name: Install rbenv
    homebrew: name=rbenv state=present
  - name: Install rbenv-default-gems
    homebrew: name=rbenv-default-gems state=present
  - name: Install rbenv-gemset
    homebrew: name=rbenv-gemset state=present
  - name: Install python
    homebrew: name=python state=present
  # Various
  - name: Install Docker
    homebrew: name=docker state=present
  - name: Install flux
    homebrew_cask: name=flux state=present
  - name: Install Go
    homebrew: name=go state=present
  - name: Install iTerm2
    homebrew_cask: name=iterm2 state=present
  - name: Install LightPaper
    homebrew_cask: name=lightpaper state=present
  - name: Install Nmap
    homebrew: name=nmap state=present
  - name: Install Packer
    homebrew: name=packer state=present
  - name: Install SourceTree
    homebrew_cask: name=sourcetree state=present
  - name: Install Stow
    homebrew: name=stow state=present
  - name: Install The Unarchiver
    homebrew_cask: name=the-unarchiver state=present
  - name: Install Transmit
    homebrew_cask: name=transmit state=present
  - name: Install Vagrant
    homebrew_cask: name=vagrant state=present
  - name: Install Vim
    homebrew: name=vim state=present
  - name: Install VirtualBox
    homebrew_cask: name=virtualbox state=present
  - name: Install Viscosity
    homebrew_cask: name=viscosity state=present
  - name: Install Visual Studio Code
    homebrew_cask: name=visual-studio-code state=present
  - name: Install VLC
    homebrew_cask: name=vlc state=present
  - name: Install VMware Fusion
    homebrew_cask: name=vmware-fusion state=present
  - name: Install Wget
    homebrew: name=wget state=present
